"""fk fixes

Revision ID: f18b301b90b9
Revises: 8c6fa94a43ea
Create Date: 2024-11-10 09:40:52.106187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f18b301b90b9"
down_revision: Union[str, None] = "4e24d7b01b61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_task_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_user_id_fkey",
        "comments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "comments_task_id_fkey",
        "comments",
        "tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("memberships_user_id_fkey", "memberships", type_="foreignkey")
    op.drop_constraint(
        "memberships_workspace_id_fkey", "memberships", type_="foreignkey"
    )
    op.create_foreign_key(
        "memberships_user_id_fkey",
        "memberships",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "memberships_workspace_id_fkey",
        "memberships",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("targets_task_id_fkey", "targets", type_="foreignkey")
    op.create_foreign_key(
        "targets_task_id_fkey",
        "targets",
        "tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "task_update_events_author_id_fkey", "task_update_events", type_="foreignkey"
    )
    op.create_foreign_key(
        "task_update_events_author_id_fkey",
        "task_update_events",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("tasks", sa.Column("files", sa.JSON(), nullable=True))
    op.add_column("tasks", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.drop_constraint("tasks_workspace_id_fkey", "tasks", type_="foreignkey")
    op.drop_constraint("tasks_author_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_workspace_id_fkey",
        "tasks",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "tasks_author_id_fkey",
        "tasks",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("workspaces", sa.Column("smtp_host", sa.String(), nullable=True))
    op.add_column("workspaces", sa.Column("smtp_port", sa.Integer(), nullable=True))
    op.add_column("workspaces", sa.Column("smtp_email", sa.String(), nullable=True))
    op.add_column("workspaces", sa.Column("smtp_password", sa.String(), nullable=True))
    op.drop_constraint("workspaces_owner_id_fkey", "workspaces", type_="foreignkey")
    op.create_foreign_key(
        "workspaces_owner_id_fkey",
        "workspaces",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("workspaces_owner_id_fkey", "workspaces", type_="foreignkey")
    op.create_foreign_key(
        "workspaces_owner_id_fkey", "workspaces", "users", ["owner_id"], ["id"]
    )
    op.drop_column("workspaces", "smtp_password")
    op.drop_column("workspaces", "smtp_email")
    op.drop_column("workspaces", "smtp_port")
    op.drop_column("workspaces", "smtp_host")
    op.drop_constraint("tasks_workspace_id_fkey", "tasks", type_="foreignkey")
    op.drop_constraint("tasks_author_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_workspace_id_fkey", "tasks", "workspaces", ["workspace_id"], ["id"]
    )
    op.create_foreign_key(
        "tasks_author_id_fkey", "tasks", "users", ["author_id"], ["id"]
    )
    op.drop_column("tasks", "is_archived")
    op.drop_column("tasks", "files")
    op.drop_constraint(
        "task_update_events_author_id_fkey", "task_update_events", type_="foreignkey"
    )
    op.create_foreign_key(
        "task_update_events_author_id_fkey",
        "task_update_events",
        "users",
        ["author_id"],
        ["id"],
    )
    op.drop_constraint("targets_task_id_fkey", "targets", type_="foreignkey")
    op.create_foreign_key(
        "targets_task_id_fkey", "targets", "tasks", ["task_id"], ["id"]
    )
    op.drop_constraint("memberships_user_id_fkey", "memberships", type_="foreignkey")
    op.drop_constraint(
        "memberships_workspace_id_fkey", "memberships", type_="foreignkey"
    )
    op.create_foreign_key(
        "memberships_user_id_fkey", "memberships", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "memberships_workspace_id_fkey",
        "memberships",
        "workspaces",
        ["workspace_id"],
        ["id"],
    )
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_task_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_user_id_fkey", "comments", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "comments_task_id_fkey", "comments", "tasks", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
